%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% XeLaTeX class for dissertations
%
% Designed for ITMO University, SCS, IAM department
%
% Created by Andrei Kuznetsov (andr.kzntsw@gmail.com)
% Distributed under LPPL 1.3+
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%% Identification

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{scs-iam}[2017/09/02 SCS IAM dissertation class]


%%% Loading 'extarticle' class

\LoadClass[a4paper,14pt]{extarticle}
